import PropTypes from 'prop-types';
import Footer from "../components/Footer";
import LegalHeader from "../components/LegalHeader";

function PrivacyPolicy({ $isDarkMode, isDarkMode }) {
  const dark = $isDarkMode ?? isDarkMode;
  const textCls = dark ? "text-gray-200" : "text-gray-800";
  const subTextCls = dark ? "text-gray-300" : "text-gray-700";
  const containerCls = dark ? "bg-gray-900 text-gray-100" : "bg-white text-gray-900";

  return (
    <div className={`min-h-screen flex flex-col ${containerCls}`}>
      <LegalHeader $isDarkMode={dark} isDarkMode={dark} />
      <main className="flex-1">
  <div className="max-w-6xl mx-auto px-4 sm:px-5 lg:px-6 py-8">
          <h1 className={`text-3xl font-bold mb-2 ${textCls}`}>Privacy Policy</h1>
          <p className={`mb-6 ${subTextCls}`}>
            <span className="font-semibold">Effective date:</span> May 10, 2025
          </p>

          <p className={`mb-6 leading-relaxed ${textCls}`}>
            This document is an electronic record in terms of the Information Technology Act, 2000 and the relevant rules under it, including amendments. This electronic record is generated by a computer system and does not require any physical or digital signatures.
          </p>

          <p className={`mb-6 leading-relaxed ${textCls}`}>
            This Privacy Policy is published in accordance with Rule 3(1) of the Information Technology (Intermediaries Guidelines) Rules, 2011, which requires the publication of privacy policies, terms of use, and rules and regulations for access or usage of the website [www.kgamify.in], including its mobile application (hereinafter referred to as the &quot;Platform&quot;).
          </p>

          <p className={`mb-6 leading-relaxed ${textCls}`}>
            The Platform is owned and operated by Yantrikisoft Pvt. Ltd., a private limited company incorporated under the Companies Act, 1956, having its registered office at D207, Shabi Complex, Plot 110-111, Sector 12, Vashi, Navi Mumbai – 400703, India (hereinafter referred to as &quot;Yantrikisoft&quot;).
          </p>

          <h2 className={`text-xl font-semibold mt-8 mb-3 ${textCls}`}>1. Introduction</h2>
          <p className={subTextCls}>When you use the Platform, we may collect personal and non-personal information such as:</p>
          <ul className={`${subTextCls} list-disc pl-6 mt-2 space-y-1`}>
            <li>Name</li>
            <li>Email address</li>
            <li>Contact number</li>
            <li>Educational background</li>
            <li>Usage behaviour, scores, and performance data</li>
            <li>Device, browser, and IP-related data</li>
          </ul>

          <h2 className={`text-xl font-semibold mt-8 mb-3 ${textCls}`}>2. How We Use Your Information</h2>
          <p className={subTextCls}>Your information may be used in:</p>
          <ul className={`${subTextCls} list-disc pl-6 mt-2 space-y-1`}>
            <li>Register and manage your account</li>
            <li>Facilitate participation in championships</li>
            <li>Provide rewards, discounts, and offers</li>
            <li>Communicate updates, offers, and support messages</li>
            <li>Improve platform functionality through analytics</li>
            <li>Generate employability and knowledge indexes via AI</li>
          </ul>
          <p className={`mt-2 ${subTextCls}`}>
            We do not sell or share your personally identifiable information with third parties for marketing purposes without your consent.
          </p>

          <h2 className={`text-xl font-semibold mt-8 mb-3 ${textCls}`}>3. Cookies &amp; Tracking</h2>
          <p className={subTextCls}>
            kGamify uses cookies and similar technologies to personalize user experience and understand usage behaviour. You can manage your cookie settings through your browser.
          </p>

          <h2 className={`text-xl font-semibold mt-8 mb-3 ${textCls}`}>4. Data Security</h2>
          <p className={subTextCls}>
            We follow industry-standard security practices to protect your personal data. While we strive to safeguard information, no system is completely immune to breaches. Verification may be required to process sensitive requests.
          </p>

          <h2 className={`text-xl font-semibold mt-8 mb-3 ${textCls}`}>5. Children’s Privacy</h2>
          <p className={subTextCls}>
            kGamify is not intended for children under 13 years of age. We do not knowingly collect personal information from minors. If found, such data will be deleted immediately.
          </p>

          <h2 className={`text-xl font-semibold mt-8 mb-3 ${textCls}`}>6. Information Sharing &amp; Disclosure</h2>
          <p className={subTextCls}>We may disclose information:</p>
          <ul className={`${subTextCls} list-disc pl-6 mt-2 space-y-1`}>
            <li>To comply with applicable laws and legal processes</li>
            <li>To protect the rights and safety of Yantrikisoft or its users</li>
            <li>To trusted partners working on our behalf under confidentiality agreements</li>
          </ul>
          <p className={`mt-2 ${subTextCls}`}>
            We may share aggregated and anonymized data with partners for analytics or business development.
          </p>

          <h2 className={`text-xl font-semibold mt-8 mb-3 ${textCls}`}>7. Access &amp; Correction</h2>
          <p className={subTextCls}>To access, correct, or delete your information, you may contact us via email at:</p>
          <p className={`mt-1 ${subTextCls}`}>
            <a href="mailto:support@kgamify.in" className="underline text-[#ff8200] hover:text-[#e57400]">support@kgamify.in</a>
          </p>

          <h2 className={`text-xl font-semibold mt-8 mb-3 ${textCls}`}>8. Changes to This Policy</h2>
          <p className={subTextCls}>
            We may update this Privacy Policy periodically. Continued use of the Platform after changes implies acceptance.
          </p>

          <h2 className={`text-xl font-semibold mt-8 mb-3 ${textCls}`}>9. Contact Us</h2>
          <address className={`${subTextCls} not-italic`}>
            Yantrikisoft Pvt. Ltd.<br />
            D207, Shabi Complex, Plot 110-111, Sector 12, Vashi, Navi Mumbai – 400703, India
          </address>
          <p className={`mt-1 ${subTextCls}`}>
            <a href="mailto:support@kgamify.in" className="underline text-[#ff8200] hover:text-[#e57400]">support@kgamify.in</a>
          </p>
          <p className={`mt-1 ${subTextCls}`}>
            <a href="https://www.kgamify.in" target="_blank" rel="noreferrer" className="underline text-[#ff8200] hover:text-[#e57400]">www.kgamify.in</a>
          </p>
        </div>
      </main>

      <Footer isDarkMode={dark} $isDarkMode={dark} />
    </div>
  );
}

PrivacyPolicy.propTypes = {
  $isDarkMode: PropTypes.bool,
  isDarkMode: PropTypes.bool,
};

export default PrivacyPolicy;
